language: python

stages:
- quality-assurance

cache: pip

jobs:
  include:
  - stage: quality-assurance
    python: '3.6'
    install: pip install flake8
    script: flake8

  - stage: quality-assurance
    python: '3.6'
    before_install:
    - pip install pytest==4.4.1 pytest-cov==2.6.1
    install:
    - python setup.py install
    script:
    - pytest --cov octconv --cov-report term-missing -v tests/
