root: ./data
dataset: imagenet
download: False
arch: resnet50
alpha: 0.5
workers: 4
epochs: 120
batch-size: 256
lr: 0.1
lr-steps: [40, 80]
lr-warmup-epochs: 5
momentum: 0.9
weight-decay: 1e-4
print-freq: 10
