root: ./data
dataset: cifar10
download: True
arch: resnet20_small
alpha: 0.5
workers: 4
epochs: 90
batch-size: 128
base-lr: 0.001
max-lr: 0.1
lr-mode: triangular2
lr-step-size: 2000
momentum: 0.9
weight-decay: 1e-4
print-freq: 10
